

# Database (MySQL)
db.url=jdbc:mysql://127.0.0.1:3306/newsnest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=Sakshi123!

# News API  →  Get your FREE key at https://newsapi.org/register
news.api.key=1a66834c0e3446ebb25fe8291210b584
news.api.base.url=https://newsapi.org/v2/top-headlines
news.default.country=us

app.name=NewsNest
